// import images
import Hero_person from "./assets/images/Hero/person.png";

import reactjs from "./assets/images/Skills/react.png";
import ps from "./assets/images/Skills/ps.png";

import services_logo1 from "./assets/images/Services/logo1.png";
import services_logo2 from "./assets/images/Services/logo2.png";
import services_logo3 from "./assets/images/Services/logo3.png";

import project1 from "./assets/images/Projects/img1.png";
import project2 from "./assets/images/Projects/img2.png";
import project3 from "./assets/images/Projects/img3.png";
import project4 from "./assets/images/Projects/img4.png";

import avatar1 from "./assets/images/Testimonials/avatar1.png";
import avatar2 from "./assets/images/Testimonials/avatar2.png";
import avatar3 from "./assets/images/Testimonials/avatar3.png";
import avatar4 from "./assets/images/Testimonials/avatar4.png";

// import icons from react-icons
import { GrMail } from "react-icons/gr";
import { MdArrowForward } from "react-icons/md";
import { BsLinkedin, BsGithub, BsWhatsapp } from "react-icons/bs";
import { TbSmartHome } from "react-icons/tb";
import { BiUser } from "react-icons/bi";
import { RiServiceLine, RiProjectorLine } from "react-icons/ri";
import { MdOutlinePermContactCalendar } from "react-icons/md";

const imgs = [project1, project2, project3, project4];

export const content = {
  nav: [
    { link: "#home", icon: TbSmartHome },
    { link: "#skills", icon: BiUser },
    { link: "#services", icon: RiServiceLine },
    { link: "#projects", icon: RiProjectorLine },
    { link: "#contact", icon: MdOutlinePermContactCalendar },
  ],
  hero: {
    title: "Full-Stack MERN & Mobile\nApplications That Scale.",
    subtitle:
      "MERN Stack Developer with 3.5+ years of experience building scalable web and mobile applications using React.js, Node.js, MongoDB, React Native, and Python/Django with AI integration.",
    firstName: "Muhammad Talha",
    LastName: "Riaz",
    btnText: "Let's Build Yours",
    image: Hero_person,
    hero_content: [
      {
        count: "3.5+",
        text: "Years of Full-Stack Development Experience",
      },
      {
        count: "15+",
        text: "Production Projects Delivered",
      },
    ],
  },
  skills: {
    title: "Skills",
    subtitle: "MY CORE SKILLS",
    skills_content: [
      {
        id: "frontend",
        name: "Frontend Development",
        para: "React.js, Next.js, Tailwind CSS, MUI, Redux Toolkit",
        logo: reactjs,
        description:
          "I build fast, scalable, and pixel-perfect UIs using React.js and Next.js with modern CSS frameworks. Proficient in Tailwind CSS, Bootstrap, MUI, React Hook Form, and Redux Toolkit for complete frontend solutions.",
        features: [
          "React.js & Next.js application development",
          "Tailwind CSS & Bootstrap responsive design",
          "Redux Toolkit & RTK Query state management",
          "Material UI (MUI) component libraries",
          "React Hook Form with validation",
          "Performance optimization & code splitting",
          "PWA (Progressive Web App) development",
        ],
        projects: [
          "SaaS dashboards",
          "Admin panels",
          "E-commerce storefronts",
          "Business platforms",
        ],
        experience: "3.5+ years",
        proficiency: 92,
      },
      {
        id: "backend",
        name: "Backend Development",
        para: "Node.js, Express.js, REST APIs, Socket.io, Microservices",
        logo: reactjs,
        description:
          "I design secure and scalable backend systems using Node.js and Express with RESTful APIs, real-time Socket.io communication, and microservices architecture. Experienced with JWT authentication and role-based access control.",
        features: [
          "RESTful API design & development with Express.js",
          "Real-time applications with Socket.io",
          "JWT authentication & role-based access control",
          "Middleware architecture & error handling",
          "Microservices architecture",
          "API security best practices",
          "Email.js & notification integration",
        ],
        projects: [
          "Real-time chat applications",
          "Multi-tenant SaaS backends",
          "Authentication & authorization systems",
        ],
        experience: "3.5+ years",
        proficiency: 90,
      },
      {
        id: "database-cloud",
        name: "Database & Cloud",
        para: "MongoDB, Firebase, AWS S3/EC2, Cloudinary, Vercel",
        logo: ps,
        description:
          "I design and optimize NoSQL databases and deploy applications on AWS and cloud platforms. Skilled in MongoDB aggregation pipelines, Firebase Firestore, AWS EC2/S3/Elastic Beanstalk, Cloudinary for media, and Stripe for payments.",
        features: [
          "MongoDB schema design & aggregation pipelines",
          "Firebase Firestore & real-time database",
          "AWS S3 for media & file storage",
          "AWS EC2 & Elastic Beanstalk deployment",
          "Cloudinary for image optimization",
          "Stripe payment gateway integration",
          "Vercel & Netlify deployment",
        ],
        projects: [
          "Analytics platforms",
          "Large-scale SaaS databases",
          "Media-heavy applications",
        ],
        experience: "2+ years",
        proficiency: 88,
      },
      {
        id: "python-django-ai",
        name: "Python, Django & AI",
        para: "Python, Django REST Framework, AI/LLM integration",
        logo: ps,
        description:
          "I build robust backend systems with Python and Django REST Framework, and integrate AI/ML capabilities into web and mobile applications. Experienced in connecting OpenAI APIs, LLM pipelines, and intelligent automation into production-ready applications.",
        features: [
          "Python & Django REST Framework APIs",
          "AI/LLM integration (OpenAI, Gemini)",
          "Intelligent chatbot development",
          "Automated data processing pipelines",
          "Machine learning model integration",
          "AI-powered feature development",
          "Natural language processing (NLP)",
        ],
        projects: [
          "AI-powered SaaS platforms",
          "Intelligent automation tools",
          "Chatbot & assistant applications",
        ],
        experience: "1+ year",
        proficiency: 80,
      },
      {
        id: "mobile",
        name: "Mobile App Development",
        para: "React Native, Flutter — cross-platform iOS & Android",
        logo: reactjs,
        description:
          "I build high-quality cross-platform mobile applications using React Native and Flutter. Delivered 7+ live mobile apps on the Google Play Store with real-time features, payment integration, GPS tracking, and smooth UX.",
        features: [
          "React Native cross-platform development",
          "Flutter app development",
          "Firebase integration & push notifications",
          "Google Maps & geolocation services",
          "Stripe & payment gateway integration",
          "HealthKit & Google Fit integration",
          "WebRTC for real-time video & audio",
        ],
        projects: [
          "Ride-sharing & transport apps",
          "Delivery & logistics apps",
          "Health & wellness apps",
          "Live streaming & social apps",
        ],
        experience: "2+ years",
        proficiency: 85,
      },
      {
        id: "devtools",
        name: "Dev Tools & DevOps",
        para: "Git/GitHub, Postman, AWS, Vercel, MicroServices",
        logo: ps,
        description:
          "I follow professional software development workflows using Git/GitHub for version control, Postman for API testing, and cloud platforms for deployment. Experienced in microservices architecture and agile development practices.",
        features: [
          "Git/GitHub version control & collaboration",
          "Postman API testing & documentation",
          "AWS EC2, S3, Elastic Beanstalk",
          "Vercel & Netlify deployment",
          "Microservices architecture",
          "Agile/Scrum development workflow",
        ],
        projects: [
          "Cloud deployments & CI/CD",
          "Team collaboration projects",
          "Production infrastructure setup",
        ],
        experience: "3.5+ years",
        proficiency: 88,
      },
    ],
    icon: MdArrowForward,
  },
  services: {
    title: "Services",
    subtitle: "WHAT I OFFER",
    service_content: [
      {
        id: "mern-development",
        title: "MERN Stack Development",
        para: "Full-stack web apps with MongoDB, Express, React & Node.js",
        logo: services_logo1,
        description:
          "I build complete, production-ready MERN stack applications with clean architecture, scalable REST APIs, and optimized databases. From SaaS platforms to admin dashboards and business management systems.",
        features: [
          "Full-stack MERN development",
          "REST API & backend architecture",
          "MongoDB database design & aggregation",
          "JWT authentication & authorization",
          "Real-time features with Socket.io",
          "Deployment on AWS / Vercel",
        ],
        technologies: ["React.js", "Node.js & Express", "MongoDB", "Redux Toolkit", "Socket.io", "JWT Authentication"],
        projects: ["SaaS platforms", "Admin dashboards", "Business management systems"],
        pricing: "Starting from $500",
        deliveryTime: "3–6 weeks",
        category: "Development",
      },
      {
        id: "frontend-development",
        title: "Frontend Development",
        para: "Modern responsive UIs with React.js, Next.js & Tailwind CSS",
        logo: services_logo2,
        description:
          "I create beautiful, fast, and responsive user interfaces using React.js, Next.js, Tailwind CSS, and MUI. Pixel-perfect designs with smooth animations, optimal performance, PWA support, and excellent user experience.",
        features: [
          "React.js & Next.js development",
          "Tailwind CSS & MUI component styling",
          "Redux Toolkit state management",
          "React Hook Form with validation",
          "PWA development",
          "SEO & performance optimization",
        ],
        technologies: ["React.js", "Next.js", "Tailwind CSS", "Bootstrap", "MUI", "Redux Toolkit"],
        projects: ["Landing pages", "E-commerce stores", "Business dashboards"],
        pricing: "Starting from $300",
        deliveryTime: "1–3 weeks",
        category: "Frontend",
      },
      {
        id: "backend-api",
        title: "Backend & API Development",
        para: "Scalable REST APIs with Node.js, Express & database integration",
        logo: services_logo3,
        description:
          "I build secure, scalable, and well-documented backend systems and REST APIs using Node.js and Express. With proper authentication, error handling, database optimization, real-time Socket.io, and Stripe payment integration.",
        features: [
          "REST API design & development",
          "JWT authentication & RBAC",
          "MongoDB aggregation pipelines",
          "Socket.io real-time features",
          "AWS S3 file uploads",
          "Stripe payment integration",
        ],
        technologies: ["Node.js", "Express.js", "MongoDB", "Socket.io", "AWS S3", "Stripe"],
        projects: ["Authentication systems", "E-commerce backends", "Real-time chat systems"],
        pricing: "Starting from $400",
        deliveryTime: "2–4 weeks",
        category: "Backend",
      },
      {
        id: "python-django-ai",
        title: "Python, Django & AI Integration",
        para: "Django REST APIs & AI-powered features for your applications",
        logo: services_logo1,
        description:
          "I build Django REST Framework APIs and integrate cutting-edge AI capabilities into your applications. From OpenAI/GPT integrations to intelligent chatbots, automated workflows, NLP, and ML-powered features.",
        features: [
          "Django REST Framework API development",
          "OpenAI / LLM API integration",
          "Intelligent chatbot development",
          "AI-powered automation workflows",
          "Natural language processing (NLP)",
          "Data analysis & automation scripts",
        ],
        technologies: ["Python", "Django", "Django REST Framework", "OpenAI API", "LangChain", "PostgreSQL"],
        projects: ["AI-powered SaaS tools", "Chatbot systems", "Automation pipelines"],
        pricing: "Starting from $500",
        deliveryTime: "2–5 weeks",
        category: "AI & Backend",
      },
      {
        id: "mobile-apps",
        title: "Mobile App Development",
        para: "Cross-platform iOS & Android apps with React Native & Flutter",
        logo: services_logo2,
        description:
          "I develop high-quality cross-platform mobile applications using React Native and Flutter. From ride-sharing apps to live streaming platforms — delivered 7+ mobile apps live on the Google Play Store.",
        features: [
          "React Native & Flutter development",
          "iOS & Android cross-platform apps",
          "Firebase & push notifications",
          "Google Maps & geolocation",
          "Stripe & payment integration",
          "WebRTC real-time video",
        ],
        technologies: ["React Native", "Flutter", "Firebase", "Google Maps API", "Stripe", "WebRTC"],
        projects: ["Ride-sharing apps", "Delivery apps", "Health & wellness apps", "Live streaming apps"],
        pricing: "Starting from $700",
        deliveryTime: "4–8 weeks",
        category: "Mobile",
      },
      {
        id: "cloud-deployment",
        title: "Cloud Deployment & DevOps",
        para: "Deploy & scale your apps on AWS, Vercel & Netlify",
        logo: services_logo3,
        description:
          "I handle deployment, scaling, and cloud infrastructure for your applications using AWS (EC2, S3, Elastic Beanstalk), Vercel, and Netlify. Ensuring high availability, security, and performance in production.",
        features: [
          "AWS EC2 server setup & configuration",
          "AWS S3 storage & CDN setup",
          "Elastic Beanstalk auto-scaling",
          "Vercel & Netlify deployment",
          "Domain & SSL configuration",
          "Performance monitoring & optimization",
        ],
        technologies: ["AWS EC2", "AWS S3", "Elastic Beanstalk", "Vercel", "Netlify", "Cloudinary"],
        projects: ["Production deployments", "Scalable cloud infrastructure", "Media-heavy platforms"],
        pricing: "Starting from $300",
        deliveryTime: "1–2 weeks",
        category: "DevOps",
      },
    ],
  },
  Projects: {
    title: "Projects",
    subtitle: "MY CREATION",
    image: Hero_person,
    project_content: [
      {
        id: "home-pro-deals",
        title: "Home Pro Deals",
        image: imgs[0],
        category: "E-commerce Platform",
        type: "React.js",
        description:
          "Complete home improvement marketplace with product listings, user reviews, seller management, and secure Stripe checkout built on the full MERN stack.",
        overview:
          "Home Pro Deals is a comprehensive home improvement e-commerce marketplace connecting buyers and sellers. It features product listings, detailed reviews, seller dashboards, and a seamless checkout experience powered by Stripe.",
        features: [
          "Multi-vendor product marketplace",
          "Advanced product search & filtering",
          "Secure Stripe payment checkout",
          "User reviews & rating system",
          "Seller management dashboard",
          "Order tracking & management",
          "Responsive mobile-friendly design",
          "MongoDB with aggregation queries",
        ],
        technologies: ["React.js", "Node.js", "Stripe", "MongoDB", "Express.js", "JWT", "AWS S3", "Redux Toolkit"],
        challenges: [
          "Building a scalable multi-vendor inventory system",
          "Integrating Stripe for secure payment flows",
          "Optimizing MongoDB queries for large catalogs",
          "Creating a smooth seller onboarding experience",
        ],
        results: [
          "Live production platform serving real users",
          "Secure Stripe payment processing",
          "Scalable MERN architecture",
          "Responsive across all devices",
        ],
        duration: "3 months",
        client: "Home Improvement Business",
        status: "Live in Production",
        demoLink: "https://homeprodeals.com/",
        githubLink: "#",
      },
      {
        id: "trace-direct",
        title: "Trace Direct",
        image: imgs[1],
        category: "Analytics Platform",
        type: "React + TypeScript",
        description:
          "Real-time tracking and analytics dashboard for business intelligence and data visualization built with D3.js and TypeScript.",
        overview:
          "Trace Direct is a powerful analytics and business intelligence platform providing real-time data tracking, interactive D3.js visualizations, and actionable insights through a modern dashboard interface.",
        features: [
          "Real-time data tracking & monitoring",
          "Interactive D3.js data visualizations",
          "Custom analytics dashboard builder",
          "Business intelligence reporting",
          "TypeScript type-safe codebase",
          "Data export (CSV, PDF)",
          "Role-based dashboard access",
          "Responsive dashboard layouts",
        ],
        technologies: ["React.js", "TypeScript", "D3.js", "Node.js", "MongoDB", "Express.js", "JWT", "REST API"],
        challenges: [
          "Building complex interactive D3.js charts",
          "Handling real-time data streams efficiently",
          "Ensuring TypeScript type safety across codebase",
          "Optimizing performance with large datasets",
        ],
        results: [
          "Live analytics platform with real-time tracking",
          "Interactive data visualizations deployed",
          "Scalable TypeScript architecture",
          "Production-ready deployment",
        ],
        duration: "2.5 months",
        client: "Analytics Startup",
        status: "Live in Production",
        demoLink: "https://run.trace.direct/",
        githubLink: "#",
      },
      {
        id: "vexion-cards",
        title: "Vexion Cards",
        image: imgs[2],
        category: "Digital Cards Platform",
        type: "Next.js",
        description:
          "Modern digital business card platform with customizable designs, QR code sharing, analytics tracking, and multi-language support built with Next.js and PostgreSQL.",
        overview:
          "Vexion Cards reimagines the traditional business card as a dynamic, shareable digital profile. Users create stunning cards, share via QR codes, and track engagement analytics — deployed on Vercel with Next.js SSR.",
        features: [
          "Customizable digital business card builder",
          "QR code generation & sharing",
          "Analytics tracking (views & clicks)",
          "Multi-language internationalization (i18n)",
          "PostgreSQL relational database",
          "Vercel edge deployment",
          "SEO-optimized with Next.js SSR",
          "Responsive across all devices",
        ],
        technologies: ["Next.js", "Tailwind CSS", "PostgreSQL", "Vercel", "Prisma ORM", "i18n", "QR Code API", "REST API"],
        challenges: [
          "Building a flexible card customization engine",
          "Implementing multi-language support",
          "Optimizing PostgreSQL queries for analytics",
          "Creating shareable card URL system",
        ],
        results: [
          "Live platform with active users",
          "Multi-language support deployed",
          "Fast SSR with Next.js on Vercel",
          "Production-ready PostgreSQL backend",
        ],
        duration: "2 months",
        client: "Digital Cards Startup",
        status: "Live in Production",
        demoLink: "https://www.vexioncards.one/en/",
        githubLink: "#",
      },
      {
        id: "gala-tab",
        title: "Gala Tab",
        image: imgs[3],
        category: "Event Management",
        type: "React.js",
        description:
          "Comprehensive event planning and management platform with venue booking, attendee management, and Stripe payment integration powered by Firebase real-time updates.",
        overview:
          "Gala Tab is a full-featured event management platform streamlining the entire event lifecycle — from venue booking and attendee registration to payment processing and post-event analytics.",
        features: [
          "Event creation & management",
          "Venue booking & availability calendar",
          "Attendee registration & ticketing",
          "Stripe payment integration",
          "Firebase real-time updates",
          "Material UI component library",
          "Email notifications",
          "Event analytics dashboard",
        ],
        technologies: ["React.js", "Firebase", "Stripe", "Material-UI", "Node.js", "Express.js", "REST API", "Email.js"],
        challenges: [
          "Building a real-time availability booking system",
          "Managing concurrent Stripe payment flows",
          "Creating an intuitive event management dashboard",
          "Implementing real-time attendee notifications",
        ],
        results: [
          "Live event management platform",
          "Stripe payment processing active",
          "Firebase real-time sync working",
          "Responsive Material UI design",
        ],
        duration: "2.5 months",
        client: "Event Planning Company",
        status: "Live in Production",
        demoLink: "https://gala-tab-fe.vercel.app/",
        githubLink: "#",
      },
      {
        id: "quaspect",
        title: "Quaspect",
        image: imgs[0],
        category: "Business Solutions",
        type: "Vue.js",
        description:
          "Professional business consulting platform with project management, client portal, business analytics, and role-based access. Built with Vue.js and Laravel on AWS infrastructure.",
        overview:
          "Quaspect is an enterprise-level business consulting platform helping companies manage projects, track deliverables, and maintain client relationships through a unified portal with powerful analytics.",
        features: [
          "Project management & tracking",
          "Client relationship management",
          "Business analytics & reporting",
          "Document management system",
          "Role-based access control",
          "MySQL relational database",
          "AWS cloud deployment",
          "Email notification system",
        ],
        technologies: ["Vue.js", "Laravel", "MySQL", "AWS EC2", "AWS S3", "PHP", "REST API", "JWT"],
        challenges: [
          "Building a complex role-based permission system",
          "Migrating to AWS cloud infrastructure",
          "Integrating Vue.js with Laravel REST API",
          "Creating a comprehensive analytics engine",
        ],
        results: [
          "Live enterprise platform",
          "AWS cloud deployment active",
          "Complex RBAC system implemented",
          "Production MySQL database optimized",
        ],
        duration: "3 months",
        client: "Business Consulting Firm",
        status: "Live in Production",
        demoLink: "https://quaspect.com/",
        githubLink: "#",
      },
      {
        id: "event-place",
        title: "Event Place",
        image: imgs[1],
        category: "Event Booking",
        type: "React.js",
        description:
          "Event venue booking platform with real-time availability calendar, integrated payment system, and seamless booking experience deployed on Netlify.",
        overview:
          "Event Place simplifies venue discovery and booking — users search venues, check real-time availability, and book with secure payments in minutes through a clean MERN stack marketplace.",
        features: [
          "Venue listing & discovery",
          "Real-time availability calendar",
          "Secure online payment system",
          "Booking confirmation & management",
          "Venue owner dashboard",
          "Search & filter by location/type",
          "Review & rating system",
          "Netlify edge deployment",
        ],
        technologies: ["React.js", "Node.js", "MongoDB", "Netlify", "Express.js", "Stripe", "JWT", "Email.js"],
        challenges: [
          "Building a reliable real-time availability system",
          "Preventing double-bookings with atomic transactions",
          "Creating intuitive venue discovery experience",
          "Optimizing search for location-based queries",
        ],
        results: [
          "Live booking platform on Netlify",
          "Real-time availability system working",
          "Secure payment processing active",
          "Smooth user booking experience",
        ],
        duration: "2 months",
        client: "Event Venue Startup",
        status: "Live in Production",
        demoLink: "https://eventplace.netlify.app/",
        githubLink: "#",
      },
      {
        id: "business-invest",
        title: "Business Invest",
        image: imgs[2],
        category: "Investment Platform",
        type: "Full-Stack",
        description:
          "Comprehensive business investment platform connecting investors with vetted opportunities, featuring portfolio tracking, deal flow management, and real-time financial analytics.",
        overview:
          "Business Invest is a full-stack investment management platform built for modern investors. It provides a streamlined interface for discovering investment opportunities, managing portfolios, tracking returns, and communicating with business owners — all in one place.",
        features: [
          "Investment opportunity listings",
          "Investor portfolio dashboard",
          "Deal flow management",
          "Real-time financial analytics",
          "Secure investor-business messaging",
          "Document management & due diligence",
          "ROI tracking & reporting",
          "Role-based access (investor / business)",
        ],
        technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "JWT", "Tailwind CSS", "Chart.js", "Cloudinary"],
        challenges: [
          "Building secure multi-role authentication for investors and businesses",
          "Designing real-time portfolio analytics with accurate financial calculations",
          "Handling sensitive financial documents with secure upload and access control",
          "Creating an intuitive deal flow pipeline for non-technical investors",
        ],
        results: [
          "Live production platform at businessinvest.com",
          "Seamless investor onboarding flow",
          "Real-time portfolio tracking dashboard",
          "Secure document management system live",
        ],
        duration: "3 months",
        client: "Business Invest",
        status: "Live in Production",
        demoLink: "https://businessinvest.com/",
        githubLink: "#",
      },
      {
        id: "fairyway-mart",
        title: "Fairyway Mart",
        image: imgs[3],
        category: "E-commerce Store",
        type: "Shopify + React",
        description:
          "Modern online shopping platform on Shopify Plus with custom React components, GraphQL Storefront API integration, inventory management, and customer analytics.",
        overview:
          "Fairyway Mart is a modern e-commerce store built on Shopify Plus with custom React components and GraphQL integration, providing a fast and personalized shopping experience with advanced inventory management.",
        features: [
          "Shopify Plus storefront",
          "Custom React component library",
          "GraphQL Storefront API integration",
          "Advanced inventory management",
          "Customer analytics dashboard",
          "Personalized product recommendations",
          "Multi-currency & payment support",
          "Mobile-first responsive design",
        ],
        technologies: ["Shopify", "React.js", "GraphQL", "Shopify Plus", "Shopify Liquid", "Storefront API", "JavaScript", "CSS"],
        challenges: [
          "Building custom React components within Shopify",
          "Optimizing GraphQL queries for large catalog",
          "Creating a flexible theme customization system",
          "Integrating advanced analytics with Shopify data",
        ],
        results: [
          "Live Shopify store in production",
          "Custom React components deployed",
          "GraphQL API integration working",
          "Improved shopping experience",
        ],
        duration: "1.5 months",
        client: "E-commerce Retail Business",
        status: "Live in Production",
        demoLink: "https://fairywaymart.com/",
        githubLink: "#",
      },
      {
        id: "fabin-drive",
        title: "Fabin Drive",
        image: imgs[0],
        category: "Mobile App",
        type: "React Native",
        description:
          "Ride-sharing and transportation mobile app with real-time GPS tracking, intelligent driver matching, and secure Stripe payments. Live on Google Play Store.",
        overview:
          "Fabin Drive is a full-featured ride-sharing application connecting passengers with drivers. Features real-time GPS via Google Maps, intelligent driver matching, fare estimation, and secure in-app Stripe payments.",
        features: [
          "Real-time GPS driver tracking",
          "Intelligent driver-passenger matching",
          "Google Maps route navigation",
          "Fare estimation & calculation",
          "Stripe payment integration",
          "Firebase real-time database",
          "Push notifications",
          "Ride history & receipts",
        ],
        technologies: ["React Native", "Firebase", "Google Maps API", "Stripe", "Node.js", "Express.js", "MongoDB", "Push Notifications"],
        challenges: [
          "Building accurate real-time location tracking",
          "Implementing intelligent driver-matching algorithm",
          "Optimizing battery usage for continuous GPS",
          "Creating smooth payment flow with Stripe",
        ],
        results: [
          "Live on Google Play Store",
          "Real-time GPS tracking operational",
          "Stripe payments processing",
          "Active users on the platform",
        ],
        duration: "4 months",
        client: "Transportation Startup",
        status: "Live on Play Store",
        demoLink: "https://play.google.com/store/apps/details?id=com.fabindrive",
        githubLink: "#",
      },
      {
        id: "zippidee",
        title: "Zippidee",
        image: imgs[1],
        category: "Mobile App",
        type: "Flutter",
        description:
          "Fast delivery and logistics mobile application with real-time order tracking, delivery management, and push notification alerts. Built with Flutter and Node.js backend.",
        overview:
          "Zippidee is a delivery and logistics app connecting customers with delivery agents for fast, reliable service. Features real-time order tracking, proof of delivery, and automated push notifications.",
        features: [
          "Real-time order tracking",
          "Delivery agent management",
          "Push notification alerts",
          "Order status management",
          "Customer & driver dashboards",
          "MongoDB backend",
          "Node.js REST API",
          "Proof of delivery",
        ],
        technologies: ["Flutter", "Node.js", "MongoDB", "Firebase Cloud Messaging", "Google Maps", "Express.js", "JWT", "Dart"],
        challenges: [
          "Accurate real-time delivery tracking",
          "Managing large numbers of concurrent deliveries",
          "Building reliable push notification system",
          "Creating intuitive driver and customer interfaces",
        ],
        results: [
          "Live on Google Play Store",
          "Real-time tracking operational",
          "Push notifications working",
          "Scalable Node.js backend",
        ],
        duration: "3 months",
        client: "Logistics Company",
        status: "Live on Play Store",
        demoLink: "https://play.google.com/store/apps/details?id=com.zippidee",
        githubLink: "#",
      },
      {
        id: "shay-better",
        title: "Shay Better",
        image: imgs[2],
        category: "Mobile App",
        type: "React Native",
        description:
          "Health and wellness mobile app with personalized recommendations, progress tracking, and HealthKit integration. Built with React Native, Redux, and Firebase.",
        overview:
          "Shay Better is a comprehensive health and wellness companion providing personalized recommendations, tracking health metrics, and integrating with HealthKit for a complete wellness experience.",
        features: [
          "Personalized wellness recommendations",
          "Progress tracking & health metrics",
          "HealthKit & Google Fit integration",
          "Redux state management",
          "Firebase Firestore database",
          "Push notifications & reminders",
          "Goal setting & achievement system",
          "Wellness content library",
        ],
        technologies: ["React Native", "Redux", "Firebase", "HealthKit", "Google Fit", "Node.js", "Push Notifications", "Async Storage"],
        challenges: [
          "HealthKit & Google Fit API integration",
          "Building personalized recommendation algorithm",
          "Ensuring user health data privacy & security",
          "Creating smooth progress tracking animations",
        ],
        results: [
          "Live on Google Play Store",
          "HealthKit integration working",
          "Personalized recommendations active",
          "Firebase backend operational",
        ],
        duration: "3.5 months",
        client: "Health & Wellness Company",
        status: "Live on Play Store",
        demoLink: "https://play.google.com/store/apps/details?id=com.shaybetter",
        githubLink: "#",
      },
      {
        id: "izik-rolling-adz",
        title: "Izik Rolling Adz",
        image: imgs[3],
        category: "Mobile App",
        type: "Flutter",
        description:
          "Digital advertising and marketing mobile platform with campaign management, AdMob integration, and real-time analytics. Built with Flutter and Firebase.",
        overview:
          "Izik Rolling Adz is a digital advertising platform enabling businesses to create, manage, and track ad campaigns. Features AdMob integration, campaign analytics, and a clean campaign management dashboard.",
        features: [
          "Digital ad campaign management",
          "AdMob ad network integration",
          "Campaign performance analytics",
          "Firebase real-time database",
          "Creative asset management",
          "Campaign scheduling & targeting",
          "Revenue tracking dashboard",
          "Push notifications",
        ],
        technologies: ["Flutter", "Firebase", "AdMob", "Firestore", "Firebase Cloud Messaging", "Google Analytics", "Dart"],
        challenges: [
          "Integrating AdMob with custom ad targeting",
          "Building real-time campaign analytics",
          "Creating an intuitive campaign builder",
          "Optimizing Flutter for media-heavy content",
        ],
        results: [
          "Live on Google Play Store",
          "AdMob integration active",
          "Real-time analytics working",
          "Campaign management deployed",
        ],
        duration: "2.5 months",
        client: "Digital Marketing Agency",
        status: "Live on Play Store",
        demoLink: "https://play.google.com/store/apps/details?id=com.fabtechsol.izikrollingadz",
        githubLink: "#",
      },
      {
        id: "bano-live",
        title: "Bano Live",
        image: imgs[0],
        category: "Mobile App",
        type: "React Native",
        description:
          "Live streaming and social media mobile app with real-time video streaming, interactive chat, and social features. Built with React Native, WebRTC, Socket.io, and AWS.",
        overview:
          "Bano Live is a live streaming and social app enabling creators to broadcast live video, interact with viewers through real-time chat, and build their following. Powered by WebRTC for high-quality streaming.",
        features: [
          "Live video streaming with WebRTC",
          "Real-time interactive chat",
          "Social following & feed",
          "Socket.io live interactions",
          "AWS media server infrastructure",
          "Gift/virtual currency system",
          "Stream recording & replay",
          "Push notifications",
        ],
        technologies: ["React Native", "WebRTC", "Socket.io", "AWS EC2", "AWS S3", "Node.js", "MongoDB", "Push Notifications"],
        challenges: [
          "Building low-latency WebRTC live streaming",
          "Scaling Socket.io for large concurrent audiences",
          "Managing AWS media infrastructure",
          "Creating smooth viewer-streamer interaction",
        ],
        results: [
          "Live on Google Play Store",
          "WebRTC streaming operational",
          "Real-time chat with Socket.io",
          "AWS infrastructure scaled",
        ],
        duration: "5 months",
        client: "Social Media Platform",
        status: "Live on Play Store",
        demoLink: "https://play.google.com/store/apps/details?id=com.bano.live",
        githubLink: "#",
      },
      {
        id: "kalyan-in-score",
        title: "Kalyan In Score",
        image: imgs[1],
        category: "Mobile App",
        type: "Flutter",
        description:
          "Sports scoring and statistics mobile app with live score updates, match tracking, and real-time push notifications. Built with Flutter and Firebase real-time database.",
        overview:
          "Kalyan In Score is a sports statistics and live scoring app delivering real-time match updates, detailed player statistics, and score tracking. Firebase ensures instant data synchronization across all devices.",
        features: [
          "Live score real-time updates",
          "Match tracking & schedules",
          "Player & team statistics",
          "Firebase real-time database",
          "Push notification alerts",
          "Historical match data",
          "Multiple sports support",
          "Offline data caching",
        ],
        technologies: ["Flutter", "Firebase", "Firebase Real-time DB", "Push Notifications", "Firestore", "FCM", "Google Analytics", "Dart"],
        challenges: [
          "Real-time score updates at high frequency",
          "Handling large sports data efficiently",
          "Building reliable push notification system",
          "Creating offline-first architecture",
        ],
        results: [
          "Live on Google Play Store",
          "Real-time Firebase sync working",
          "Push notifications operational",
          "Fast and responsive Flutter UI",
        ],
        duration: "2 months",
        client: "Sports Data Company",
        status: "Live on Play Store",
        demoLink: "https://play.google.com/store/apps/details?id=com.kalyaninscore",
        githubLink: "#",
      },
      {
        id: "sahulat-app",
        title: "Sahulat App",
        image: imgs[2],
        category: "Mobile App",
        type: "React Native",
        description:
          "Multi-service utility mobile app providing daily life services including payments, bookings, and convenience features with integrated payment gateway.",
        overview:
          "Sahulat App is a super-app consolidating multiple daily utility services into a single mobile platform. Users make payments, book services, and access convenience features through a unified, easy-to-use interface.",
        features: [
          "Multi-service utility platform",
          "Integrated payment gateway",
          "Service booking & scheduling",
          "Node.js REST API backend",
          "MongoDB database",
          "Push notifications",
          "User wallet & transactions",
          "Service provider management",
        ],
        technologies: ["React Native", "Node.js", "MongoDB", "Payment Gateway", "Express.js", "JWT", "Push Notifications", "Firebase"],
        challenges: [
          "Building a unified multi-service architecture",
          "Integrating multiple payment gateway providers",
          "Managing complex service provider workflows",
          "Creating intuitive navigation for multiple services",
        ],
        results: [
          "Live on Google Play Store",
          "Payment gateway integrated",
          "Multiple services operational",
          "Node.js backend scaled",
        ],
        duration: "4 months",
        client: "Utility Services Company",
        status: "Live on Play Store",
        demoLink: "https://play.google.com/store/apps/details?id=com.sahulatapp",
        githubLink: "#",
      },
      {
        id: "rag-ai-application",
        title: "RAG AI Application",
        image: imgs[3],
        category: "AI / LLM",
        type: "Python / AI",
        description:
          "Retrieval-Augmented Generation (RAG) application that lets users chat with their own documents using AI — upload PDFs, ask questions, and get accurate answers grounded in your content.",
        overview:
          "This RAG application combines vector search with large language models to enable intelligent document Q&A. Users upload documents which are chunked, embedded, and stored in a vector database. Queries are semantically matched to relevant chunks and passed to an LLM to generate accurate, context-aware answers.",
        features: [
          "PDF / document upload & parsing",
          "Text chunking & vector embedding",
          "Semantic similarity search",
          "LLM-powered Q&A over documents",
          "Chat history & session management",
          "Source citation for each answer",
          "React.js frontend with clean UI",
          "REST API backend in Python",
        ],
        technologies: ["Python", "FastAPI", "LangChain", "OpenAI API", "Pinecone / FAISS", "React.js", "Tailwind CSS", "Vercel"],
        challenges: [
          "Chunking documents effectively to preserve context",
          "Optimising embedding and retrieval speed for large files",
          "Preventing hallucinations with accurate source grounding",
          "Building a responsive chat UI with streaming LLM responses",
        ],
        results: [
          "Live demo deployed on Vercel",
          "Accurate document Q&A with source citations",
          "Sub-second retrieval from vector store",
          "Clean React chat interface with streaming",
        ],
        duration: "3 weeks",
        client: "Personal / AI Research",
        status: "Live Demo",
        demoLink: "https://rag-application-fe.vercel.app/",
        githubLink: "#",
      },
      {
        id: "realist-system",
        title: "Realist System",
        image: imgs[0],
        category: "Real Estate",
        type: "React.js (Frontend)",
        description:
          "Modern real estate management frontend for browsing, filtering, and managing property listings with an intuitive UI built in React.js and Tailwind CSS.",
        overview:
          "Realist System is a frontend-only real estate platform that delivers a polished property browsing experience. Users can search and filter listings by location, price, and type, view detailed property pages, and connect with agents — all through a fast, responsive React.js interface.",
        features: [
          "Property listing grid with filters",
          "Location, price & type search",
          "Detailed property pages",
          "Agent contact & inquiry forms",
          "Responsive for mobile & desktop",
          "Smooth animations & transitions",
          "Featured & recommended sections",
          "Modern card-based UI",
        ],
        technologies: ["React.js", "Tailwind CSS", "React Router", "Axios", "Vercel", "CSS Animations", "React Icons"],
        challenges: [
          "Building complex filter state management without a backend",
          "Keeping the UI fast with many property card renders",
          "Designing a clean, professional real-estate aesthetic",
          "Making advanced search intuitive on mobile devices",
        ],
        results: [
          "Live on Vercel — realist-system-pink.vercel.app",
          "Fully responsive across all screen sizes",
          "Smooth filter & search experience",
          "Professional real-estate UI delivered",
        ],
        duration: "2 weeks",
        client: "Real Estate Client",
        status: "Live (Frontend)",
        demoLink: "https://realist-system-pink.vercel.app/",
        githubLink: "#",
      },
    ],
  },
  Testimonials: {
    title: "Testimonials",
    subtitle: "MY CLIENT REVIEWS",
    testimonials_content: [
      {
        review:
          '"Working with Talha Riaz in mobile app development was a FANTASTIC experience! His professionalism and thorough documentation made the process seamless. Moreover, his quick responsiveness and proactive communication truly stood out."',
        img: avatar1,
        name: "Daniel Carter",
      },
      {
        review:
          '"I had a bug that I could not seem to figure out. Talha Riaz is a very technical guy — when confronted with the bug he showed superb understanding. Delivery was extremely fast, and I\'m happy with the result. Would Highly Recommend."',
        img: avatar2,
        name: "David William",
      },
      {
        review:
          '"Talha Riaz exceeded all expectations. He was highly responsive, quick with updates, and proactive with valuable suggestions. The app is smooth, user-friendly, and professionally designed. Communication was excellent throughout. I highly recommend Talha Riaz to anyone looking for a skilled and reliable developer."',
        img: avatar3,
        name: "Michael Reyes",
      },
      {
        review:
          '"He delivered a high-quality app with excellent performance and a clean, modern design. His communication was prompt and professional, and he handled feedback with efficiency and care. I\'m very satisfied with the results and would definitely work with him again."',
        img: avatar4,
        name: "Jonathan Malik",
      },
    ],
  },
  Hireme: {
    title: "Hire Me",
    subtitle: "FOR YOUR PROJECTS",
    image1: Hero_person,
    image2: Hero_person,
    para: "Looking for a skilled MERN Stack Developer with experience in Python, Django, AI integration, and mobile app development? I'm available for freelance projects, full-time positions, and contract work. Let's build something great together.",
    btnText: "Hire Me",
  },
  Contact: {
    title: "Contact Me",
    subtitle: "GET IN TOUCH",
    social_media: [
      {
        text: "muhammadtalha1005@gmail.com",
        icon: GrMail,
        link: "mailto:muhammadtalha1005@gmail.com",
        category: "professional",
      },
      {
        text: "WhatsApp",
        icon: BsWhatsapp,
        link: "https://wa.me/923472916962",
        category: "social",
      },
      {
        text: "LinkedIn",
        icon: BsLinkedin,
        link: "https://www.linkedin.com/in/muhammad-talha-riaz-23779423b",
        category: "social",
      },
      {
        text: "GitHub",
        icon: BsGithub,
        link: "https://github.com/talhariaz78600",
        category: "social",
      },
    ],
  },
  Footer: {
    text: "All © Copy Right Reserved 2026",
  },
};
